// Master style list for the prompt taxonomy — researched, text-free, prompt-ready.
// 272 visual rendering styles spanning photography, classical & modern
// painting, world/folk/indigenous traditions, illustration/digital/3D, printmaking
// & craft, and contemporary/genre aesthetics. None depend on rendered text.
export const STYLES = [
  "studio portrait photography, soft key light",
  "environmental portrait, subject in their setting",
  "candid street photography, available light",
  "sweeping landscape photography, golden hour",
  "macro photography, extreme close-up detail",
  "wildlife photography, telephoto in natural habitat",
  "astrophotography, starry night sky",
  "star trail long-exposure, circular sky arcs",
  "architectural photography, clean geometric lines",
  "fashion editorial photography, dramatic styling",
  "documentary reportage photography, raw realism",
  "still life photography, arranged objects",
  "food photography, soft natural light",
  "product photography, crisp studio lighting",
  "cinematic photography, shallow depth of field",
  "bokeh-heavy portrait, dreamy background blur",
  "long-exposure photography, silky motion blur",
  "tilt-shift photography, miniature-model effect",
  "double-exposure photography, layered imagery",
  "infrared photography, surreal white foliage",
  "high-speed photography, frozen splash",
  "light painting photography, glowing light trails",
  "drone aerial photography, top-down view",
  "fisheye photography, ultra-wide distortion",
  "panning photography, motion-blurred background",
  "underwater photography, diffused aquatic light",
  "night photography, neon-lit city",
  "silhouette photography, backlit contours",
  "chiaroscuro photography, dramatic light and shadow",
  "low-key photography, deep shadows",
  "high-key photography, bright airy tones",
  "blue hour photography, cool twilight tones",
  "sports action photography, frozen peak moment",
  "travel photography, vivid sense of place",
  "daguerreotype, mirrored silver plate",
  "tintype, dark metallic plate portrait",
  "ambrotype, glass-plate positive",
  "wet-plate collodion, hand-coated imperfections",
  "cyanotype, deep Prussian blue print",
  "calotype, soft paper-negative print",
  "albumen print, glossy purplish-brown tones",
  "platinum-palladium print, rich tonal range",
  "gum bichromate print, painterly broad tones",
  "gelatin silver print, classic black-and-white",
  "vintage Polaroid, instant film with soft borders",
  "lomography, saturated lo-fi vignetting",
  "cross-processed film, shifted surreal colors",
  "black-and-white film noir, high-contrast shadows",
  "sepia-toned vintage photograph, warm brown tones",
  "35mm grainy film photography, analog texture",
  "photogram, white silhouettes on dark ground",
  "Italian Renaissance oil painting, sfumato modeling",
  "High Renaissance fresco, balanced classical composition",
  "Early Netherlandish oil painting, jewel-like detail",
  "Venetian Renaissance oil, warm glowing color",
  "Mannerist painting, elongated figures, acid color",
  "Baroque oil painting, dramatic chiaroscuro",
  "Caravaggesque tenebrism, single-source light",
  "Dutch Golden Age oil, soft interior light",
  "Rembrandt-style portrait, warm shadow and glow",
  "Flemish Baroque oil, fleshy exuberant color",
  "Spanish Baroque still life, austere dark ground",
  "Rococo painting, pastel palette, feathery brushwork",
  "Neoclassical oil, smooth surface, crisp contours",
  "Romantic landscape painting, sublime stormy light",
  "Turner-style atmospheric oil, luminous haze",
  "Hudson River School landscape, glowing vistas",
  "Realist oil painting, unidealized everyday subjects",
  "Barbizon-style plein-air landscape, muted tones",
  "Pre-Raphaelite oil, vivid detail, jewel color",
  "Impressionist painting, broken color, dappled light",
  "Pointillist painting, tiny dots of pure color",
  "Post-Impressionist oil, bold expressive brushwork",
  "Van Gogh-style impasto, swirling vibrant strokes",
  "Cezanne-style faceted planes, structured color patches",
  "Symbolist painting, dreamlike mystical mood",
  "Fauvist painting, wild non-naturalistic color",
  "German Expressionist oil, jagged emotional color",
  "Analytic Cubism, fractured monochrome facets",
  "Synthetic Cubism, flat overlapping color shapes",
  "Futurist painting, dynamic motion lines, speed",
  "Dada collage-style assemblage, absurd juxtaposition",
  "Surrealist painting, uncanny dreamlike imagery",
  "Dali-style oil, hyper-detailed melting forms",
  "Metaphysical painting, eerie deserted plazas",
  "De Stijl geometric abstraction, primary blocks and grids",
  "Constructivist abstraction, bold diagonal geometry",
  "Bauhaus geometric abstraction, clean color planes",
  "Abstract Expressionist canvas, gestural drips",
  "action painting, splattered energetic marks",
  "Color Field painting, vast soft-edged color planes",
  "Rothko-style stacked luminous color rectangles",
  "Pop Art painting, flat bold commercial color",
  "Ben-Day dot comic painting style, flat primaries",
  "Op Art, high-contrast optical illusion patterns",
  "Minimalist painting, single color, austere geometry",
  "hard-edge abstraction, crisp flat color shapes",
  "Photorealist painting, sharp photographic detail",
  "Hyperrealist oil, exaggerated lifelike detail",
  "Neo-Expressionist painting, raw vigorous brushwork",
  "oil painting, thick impasto texture",
  "watercolor painting, soft transparent washes",
  "gouache painting, opaque matte flat color",
  "egg tempera painting, fine cross-hatched layers",
  "buon fresco, chalky matte plaster surface",
  "soft pastel painting, velvety blended pigment",
  "acrylic painting, vivid flat saturated color",
  "encaustic painting, glossy translucent wax layers",
  "charcoal drawing, smudged tonal shading",
  "sanguine red-chalk drawing, warm earthy tone",
  "ink wash painting, fluid gray gradients",
  "silverpoint drawing, delicate fine metallic lines",
  "grisaille painting, monochrome gray tonal modeling",
  "oil glazing, luminous translucent layered color",
  "ukiyo-e woodblock print, flat color planes",
  "mokuhanga water-based woodblock print, soft gradients",
  "sumi-e ink wash, minimal brushwork",
  "nihonga mineral-pigment painting on silk",
  "Chinese shan shui ink landscape",
  "gongbi fine-line court painting, vivid color",
  "Chinese nianhua New Year woodblock print",
  "Korean minhwa folk painting, bold symbolic motifs",
  "Tibetan thangka, gridded sacred iconography",
  "Mughal miniature, layered jewel-tone detail",
  "Rajput miniature painting, flat bright color",
  "Madhubani painting, dense line and pattern",
  "Warli tribal art, white geometric figures",
  "Gond art, fine dotted-line fill",
  "Pattachitra scroll painting, ornate borders",
  "Kalighat painting, bold sweeping brush figures",
  "Kalamkari hand-painted textile motifs",
  "Pichwai painting, Krishna lotus motifs",
  "Balinese Kamasan painting, stylized epic scenes",
  "Indonesian batik, wax-resist crackled dye patterns",
  "Thai temple mural, gold-outlined celestial figures",
  "Persian miniature, jewel color and flat perspective",
  "Ottoman miniature, flat narrative composition",
  "Islamic geometric tilework, interlacing stars",
  "arabesque ornament, endless floral scrollwork",
  "Persian arabesque tile mosaic, turquoise floral lattice",
  "Tingatinga painting, bold flat enamel colors",
  "Ndebele wall design, vivid geometric panels",
  "Adinkra stamped motifs, symbolic emblems",
  "Kuba cloth pattern, woven geometric rhythm",
  "bogolan mud-cloth, earthy geometric motifs",
  "Huichol yarn painting, pressed bright yarn",
  "alebrije style, fantastical creature, vivid patterns",
  "Otomi Tenango embroidery, flat colorful animals",
  "Talavera pottery motifs, blue floral glaze",
  "Kuna mola, layered reverse-applique color",
  "papel picado, perforated tissue-paper cutwork",
  "Inuit printmaking, clean stylized arctic forms",
  "Pacific Northwest formline, swelling black-and-red curves",
  "Pre-Columbian codex style, flat profile figures",
  "Andean tocapu textile, checkered geometric blocks",
  "Aboriginal dot painting, earth-tone stippling",
  "Maori kowhaiwhai, curling koru scroll patterns",
  "Papua New Guinea bark painting, bold totemic motifs",
  "Russian lubok print, naive bright woodcut figures",
  "Scandinavian rosemaling, flowing flower scrollwork",
  "Polish wycinanki papercut, symmetrical floral roosters",
  "Ukrainian petrykivka, lush decorative flower painting",
  "Byzantine icon, gold-ground flattened figures",
  "Pennsylvania Dutch fraktur motifs, tulips and birds",
  "Hungarian Kalocsa embroidery, dense floral bloom",
  "Egyptian tomb painting, flat profile registers",
  "Aztec featherwork mosaic, iridescent tiled color",
  "woodcut relief print, bold black lines",
  "linocut print, carved flat planes",
  "wood engraving, fine end-grain white lines",
  "etching, fine cross-hatched intaglio lines",
  "drypoint print, soft velvety burr lines",
  "mezzotint, dark-to-light velvety tones",
  "aquatint, grainy tonal washes",
  "copperplate engraving, crisp burin lines",
  "lithograph, soft crayon-drawn texture",
  "screenprint, bold flat color separations",
  "risograph print, grainy overprinted spot colors",
  "letterpress impression, debossed inked texture",
  "scratchboard art, white lines scratched from black",
  "stained glass, leaded jewel-tone panels",
  "glass mosaic, shimmering tesserae",
  "smalti gold-ground mosaic",
  "pietra dura, inlaid semiprecious stone picture",
  "wood marquetry, inlaid veneer patterns",
  "intarsia wood inlay, tonal grain shading",
  "embroidered satin-stitch threadwork",
  "crewel wool embroidery, raised stitches",
  "cross-stitch, gridded pixel-like stitches",
  "zardozi metallic-thread embroidery, raised gold",
  "kantha running-stitch quilted textile",
  "woven tapestry, rich interlaced wool",
  "Navajo woven rug, geometric motifs",
  "kilim flat-weave, angular geometric pattern",
  "patchwork quilt, pieced fabric blocks",
  "applique textile, layered cut-cloth shapes",
  "paper quilling, rolled coiled paper strips",
  "layered papercut diorama, shadowed depth",
  "kirigami, cut-and-folded paper relief",
  "origami, folded geometric paper forms",
  "jianzhi papercut, intricate red silhouette",
  "pyrography, scorched woodburned shading",
  "sand art, layered colored-sand granules",
  "felted wool art, soft matted fibers",
  "flat vector illustration, bold shapes",
  "material design, flat layered surfaces",
  "corporate memphis flat illustration",
  "isometric 3D render, soft shadows",
  "low-poly 3D render, faceted geometry",
  "voxel art, cubic 3D blocks",
  "pixel art, crisp dithered sprites",
  "8-bit pixel art, limited palette",
  "16-bit pixel art, rich shading",
  "cel-shaded 3D, bold outlines",
  "toon-shaded render, flat cartoon look",
  "Pixar-style 3D, rounded expressive characters",
  "DreamWorks-style 3D, semi-realistic characters",
  "Octane render, glossy photoreal CGI",
  "Unreal Engine render, cinematic realtime",
  "clay render, soft studio lighting",
  "matte painting, sweeping digital vista",
  "concept art, painterly digital rendering",
  "digital painting, blended brushstrokes",
  "stylized 3D render, painterly textures",
  "splatter ink illustration, energetic spatters",
  "children's book illustration, soft whimsy",
  "storybook gouache, textured matte color",
  "anime, clean cel-shaded characters",
  "manga line art, dynamic screentones",
  "Studio Ghibli-esque, watercolor backgrounds",
  "Korean webtoon style, soft digital shading",
  "chibi illustration, cute exaggerated proportions",
  "retro 1950s UPA cartoon, flat modernist shapes",
  "mid-century modern flat cartoon",
  "rubber-hose animation, bouncy curved limbs",
  "claymation look, fingerprinted clay figures",
  "stop-motion puppet look, tactile sets",
  "papercut animation, layered paper cut-outs",
  "airbrushed retro-futurist illustration",
  "vibrant cartoon vector, thick clean outlines",
  "vaporwave aesthetic, pastel neon gradients",
  "synthwave illustration, neon grid sunset",
  "outrun aesthetic, neon grid and striped sun",
  "cyberpunk, rain-soaked neon dystopia",
  "solarpunk, lush greenery and clean tech",
  "steampunk, brass gears and Victorian machinery",
  "dieselpunk, interwar Art Deco machinery",
  "biopunk, organic body-horror biotech",
  "atompunk, midcentury Space Age optimism",
  "cottagecore, soft pastoral romanticism",
  "dark academia, moody candlelit scholarship",
  "dark cottagecore, shadowed botanical whimsy",
  "brutalist concrete, raw monolithic forms",
  "Memphis design, playful squiggles and pastel geometry",
  "Art Nouveau, flowing organic whiplash curves",
  "Art Deco, streamlined chevrons and sunrays",
  "psychedelic 60s, swirling kaleidoscopic color",
  "glitch art, pixel-sorted distortion",
  "datamosh smearing, pixel-bleed distortion",
  "holographic iridescence, oil-slick rainbow sheen",
  "Y2K chrome, glossy metallic futurism",
  "ferrofluid art, spiky magnetic black liquid",
  "fluid art, marbled paint pour swirls",
  "light-and-shadow minimalism, stark negative space",
  "postmodern maximalism, clashing patterns and color",
  "Afrofuturism, neon-edged ancestral futurism",
  "Gulf futurism, glossy dystopian desert hypermodernity",
  "Streamline Moderne, aerodynamic curved chrome",
  "frutiger aero, glossy translucent nature-tech",
  "liminal space, eerie empty interiors",
  "cybersigilism, spiky organic tribal linework",
  "acid graphics, chrome blobs and warped 3D"
];
